# Basic
title: HeroCat
subtitle: PM & UXer
welcome_message: <a target="_blank" href="http://blog.herocat.cn">梦想 · 自由</a>
description: Hi，我是燕凯(HeroCat)，一名PM&UXer，现居北京。喜欢产品设计和体验新技术，爱分享！目前在探索新零售的路上...
creator: <a href="http://blog.herocat.cn">@herocat</a>

url: "http://blog.herocat.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Cat's Blog

# Navigation buttons in the front page.
nav:
    - {title: 分类, description: home, url: 'http://blog.herocat.cn'}
    - {title: 关于, description: home, url: 'http://blog.herocat.cn'}
    - {title: 订阅, description: home, url: 'http://blog.herocat.cn/feed.xml'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: herocat
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: herocat
    twitter: yankaia
    gplus: 
    mail: yankai@herocat.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
